#include <stdio.h>

int main(){
	printf("Hello world! \n");
	return 0;
}

// Compilación
// Nornmalmente para compilar un archivo de c desde la terminal podemos utilizar gcc -c file_name.c que genera un archivo binario con terminación en .o el cual contiene las instrucciones que van a decirle al procesador como proceder 


// Archivos .o
// The .o files are object files generated by the compiler during the compilation process. They contain machine code that has been compiled from the source code and are used by the linker to create the final executable file.

// linking
// The linking process is the final step in the compilation of a program. It takes one or more object files generated during the compilation process and combines them into a single executable file. The linker is responsible for this process.

// Los archivos .o no se puede utilizar por si solos
// gcc hello.o genera un archivo a.out que ya es un ejecutable

// gcc -o hello hello.o --> la bandera -o sirve para cambiar el nombre al ejecutable 

// * Es por esta razon que se deben compilar los archivos con gcc en vscode para que se pueda crear un ejecutable 



